# This is a basic workflow to help you get started with Actions

name: build_linux
on:
  push:
  pull_request:

  
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Odin build
        run: odin build .
        
